DATA: # arguments that will be passed to get_dataloaders
  batch_size: 32
  points_per_circle: 3

MODEL:
  model_name: MLP
  PARAMS: # arguments that will be passed to the chosen models
    input_dim: 6
    output_dim: 1
    n_hidden: 1
    latent_dim: 32

TRAINING: # arguments that will be passed to the trainer
  criterion_str: MSELoss
  optimizer_str: Adam
  lr: 0.001
  epochs: 30
  logdir: "./logs/MLP/"
  use_logger: True
  lr_scheduler:
    lr_scheduler_name: ExponentialLR
    PARAMS:
      gamma: 0.995

SWEEP: # arguments to sweep over and their values
  latent_dim: [32, 64]
  points_per_circle:
    min: 3
    max: 10
    n: 3
  lr:
    min: 0.0001
    max: 0.001
    n: 2
    logspace: True